language: go
os:
  - linux
env:
  matrix:
    - BOARD="esp8266:esp8266:generic" CLI_VERSION="0.2.1-alpha.preview"
install:
  - go get -u github.com/arduino/arduino-cli
  - which arduino-cli
  - arduino-cli core update-index
  - arduino-cli core install esp8266:esp8266:generic
  - touch $TRAVIS_BUILD_DIR/espbutton_simple/Secrets.h
  - touch $TRAVIS_BUILD_DIR/espbutton_lowpower/Secrets.h
  - touch $TRAVIS_BUILD_DIR/espbutton_multipress/Secrets.h
script:
  - arduino-cli compile --fqbn $BOARD $TRAVIS_BUILD_DIR/espbutton_simple/espbutton_simple.ino
  - arduino-cli compile --fqbn $BOARD $TRAVIS_BUILD_DIR/espbutton_lowpower/espbutton_lowpower.ino
  - arduino-cli compile --fqbn $BOARD $TRAVIS_BUILD_DIR/espbutton_multipress/espbutton_multipress.ino
