language: generic
env:
  global:
    - CLI_VERSION=latest
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mv arduino-cli $HOME/bin/arduino-cli
  - mkdir -p $HOME/bin
  - arduino-cli config init
  - mv $PWD/.cli-config.yml $HOME/.arduino15/arduino-cli.yaml
  - arduino-cli config dump
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli core install esp8266:esp8266
  - buildSketchEsp8266() { arduino-cli compile --fqbn esp8266:esp8266:generic $PWD/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - touch espbutton_lowpower/Secrets.h
  - touch espbutton_multipress/Secrets.h
  - touch espbutton_simple/Secrets.h
script:
  - buildSketchEsp8266 "espbutton_lowpower"
  - buildSketchEsp8266 "espbutton_multipress"
  - buildSketchEsp8266 "espbutton_simple"
